### ISSUE TITLE
No background in reading mode

### ISSUE THREAD

**Issue by aryan8923** [shmolf/obsidian-editor-background#13]
The background image stops showing when switched to reading mode.

**Comment by OPEN1004MIND** [comment]
The description says it only works in edit mode, but I hope it works in read mode as well.

**Comment by shmolf** [comment]
Yes, the background is currently setup just for Edit Mode.

I can work on optionally allowing it to render in Reading Mode as well, but at the moment, I'm deep in classes + work, and don't have the time/energy to extend it.
I will seek to do it before the end of the year.

**Comment by aryan8923** [comment]
Sure, that's fine. Good Luck with your studies!
